ssh:
  user: root
  pass: ca$hc0w

load:
  heavy:
    ratio: 20
    p_num: 15
    c_num: 15
    ratelimit: 20
    maxsize: 200
    minsize: 100
  medium:
    ratio: 20
    p_num: 10
    c_num: 10
    ratelimit: 10
    maxsize: 100
    minsize: 50
  lite:
    ratio: 30
    p_num: 5
    c_num: 5
    ratelimit: 2
    maxsize: 100
    minsize: 10

output_dir: /var/vcap/data/density_test/logs
local_db: sqlite:/home/gaoyin/git/dev/density_client/new_db.db
node_ip: 10.42.122.120
plan: "100"
version: "2.8"
service_num: 3
nats_url: nats://nats:Z2b3ij3122@10.42.122.41:4222
nats_channel: RMQaaS.provision.rabbit_node_100_0
rabbit_db_file: /var/vcap/store/rabbit/rabbit_node.db
